### ISSUE TITLE
mapperFromUnderscoreCaseToCamelCase doesn't work with numbers

### ISSUE THREAD

**Issue by billinghamj** [JSONModel/JSONModel#116]
Example property name:
artifactToleranceFactor1

Expected result:
artifact_tolerance_factor_1

Actual result:
artifact_tolerance_factor1

I had a quick go at fixing this myself, but I didn't get very far.

Would this be considered a bug, or would creating a new mapper be more appropriate?

**Comment by kientux** [comment]
Sorry for bring this up, but my json has some properties like `address1`, `option1`,... and I have identical Obj-C properties `address1`, `option1`... But they're all `nil` because of this, right? I have to add custom key mapper:

```Objective-C
+ (JSONKeyMapper *)keyMapper {
    return [JSONKeyMapper mapper:[super keyMapper]
                  withExceptions:@{
                                   @"address1" : @"address1",
                                   @"option1" : @"option1"
                                   }];
}
```

which looks pretty akward. `option1` -> `option_1`, is this how it supposed to be in camelCase?

**Comment by billinghamj** [comment]
@kientux It's not possible to convert between camel case and snake case in a "lossless" manner - ultimately you have to decide between adding underscores before numbers or not.

If the option we chose doesn't match your case, you probably should copy the `mapperFromUnderscoreCaseToCamelCase` code and make your own version which works the way you'd prefer.

If you need to continue this discussion, open a new issue about it - no need to send notifications to the people in this thread :)
