### ISSUE TITLE
Convert array of JSONModel objects

### ISSUE THREAD

**Issue by arunahk** [JSONModel/JSONModel#167]
I have a JSON response which contains array of JSONModel objects inside the array. How can I convert to NSArray<JSONModel> by using AFHTTPClient as the http client?

JOSN--
[{id:1, name:"aaa"},
{id:2, name:"bbb"},
{id:3, name:"ccc"]

**Comment by billylo1** [comment]
I have a similar request... if I have {"ids":[1,2,3]} as input, how should I model it?  NSArray<NSNumber> ids does not work and it did not seem to want to deserialize the numbers.  thx.

**Comment by LilJeff2626** [comment]
if the response were {"languages":["en","us","ge"]}

How would you do it, I keep getting an error.

Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<LoanModel 0x7c5d3ce0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key description.'

Using 

@property (strong, nonatomic) NSMutableArray<NSString*>* languages;

**Comment by billinghamj** [comment]
@LilJeff2626 This is not a related issue. Open a new issue with full source code if you need help.
