### ISSUE TITLE
How to parse json array to array of NSInteger

### ISSUE THREAD

**Issue by smidaharoun** [jsonmodel/jsonmodel#540]
How to convert the following json to two arrays of `NSInteger` one containing the id of images the other contain the id of categories. 
Or do I have to create to `JSONModels`  for image and for category
```
"associations": {
        "categories": [
          {
            "id": "2"
          },
          {
            "id": "20"
          }
        ],
        "images": [
          {
            "id": "51"
          },
          {
            "id": "52"
          },
          {
            "id": "53"
          },
          {
            "id": "54"
          },
          {
            "id": "55"
          },
          {
            "id": "56"
          },
          {
            "id": "57"
          },
          {
            "id": "58"
          },
          {
            "id": "59"
          },
          {
            "id": "60"
          }
        ]
```

**Comment by behrad-kzm** [comment]
i prefer to create JSONModel for both image and category because if anytime image has new property , you can customize imageModel 
i think it increases readability.

**Comment by billinghamj** [comment]
JSONModel is designed to map JSON to/from Obj-C classes of the same structure. It does not support particularly complex mapping behavior. This is intentional.

Just deserialize into a model which includes a class for the object containing the `id` field, then iterate over the resulting arrays to turn it into an NSArray of NSNumbers (you can't have an NSArray of NSIntegers).

**Comment by smidaharoun** [comment]
Thanks @behrad-kzm  and @billinghamj That's what I did in the end.
