### ISSUE TITLE
Why deprecated convertValue:isImportingToModel ?

### ISSUE THREAD

**Issue by mario-epsilon** [jsonmodel/jsonmodel#582]
This issue is concerning a useful feature which existed in older versions of JSONModel and now it seems to be removed, we would like it back.
We have projects which use 
`-(NSString*)convertValue:(NSString*)value isImportingToModel:(BOOL)importing`
in the JSONKeyMapper class. We rely on the conversion both ways from JSON to Model and vice versa. Now, we decided to update to the most recent JSONModel and noticed that the above method is deprecated. In fact it is not deprecated in a nice way, namely if we choose to use it in the updated JSONModel, it will be the same as using convertValue: which doesn't do what we want. It would be nice that you would not replace the implementation of the deprecated method, or at least replace it with a method which can do the same thing as before. 
Now, we have to either not use the updated JSONModel, or write our own method to do the two way conversion. That's not a big deal for our new project, but our old project will break if we decide to pull updated JSONModel (being a sub-module).
I would like to know if in the current JSONModel there is a utility for two way conversion, and if not, why this feature was removed, and if we can expect something replacing it in future.
Thanks

**Comment by billinghamj** [comment]
JSONModel does convert both ways, but that particular function was very misleading, because it was actually only ever called in one direction. In reality, although it was possible to define a JSON-to-model mapping, it was never _ever_ used (and would not have been appropriate to be used), so I removed it.

Mapping in either direction does still work, and can be achieved through the model-to-JSON mapping. :)

The specific function in question should not have been used externally, I believe it was actually an internal method, or at least that was its intention.

Let me know more specifically what exactly you're trying to achieve, and I will see how I can assist. Please provide example code and what the expected results are etc.

**Comment by mario-epsilon** [comment]
Thanks for your response and also the excellent JSONModel library.

Well, I suppose the use case that we found for that method was not intended by the creator of the method. We were trying to take advantage of that method which was apparently public at least in version 1.0.2, in order to get the name of an individual property when JSON name is known:
`    NSString *propertyName = [[[self class] keyMapper] convertValue:json isImportingToModel:NO];
`
We could simply hold on to our JSON<->model mapping dict in memory and retrieve the property name if we wanted to instead (this is what we do in our new project). We couldn't find a way to achieve the same thing in current version of JSONModel though.

**Comment by billinghamj** [comment]
I would suggest that it would be best to keep that in your own code. Most of the work I've done recently in JSONModel is to deprecate and strip out any functionality which isn't core to what JSONModel exists for. This was to simplify the project as a whole and make it more maintainable.
