### ISSUE TITLE
Please create a release tag for the recent changes, which is in master

### ISSUE THREAD

**Issue by joylogs** [jsonmodel/jsonmodel#623]
1.7.0 was created on October 7, 2016

**Comment by billinghamj** [comment]
Sorry for the delay, I had some problems with Xcode 10 compatibility and CocoaPods before the v1.6.0 beta.

I have now pushed v1.8.0. Although it's really more of a patch release, I think it's safer to indicate the more significant changes since I wouldn't be surprised if there were a couple of issues which have gone unnoticed so want to avoid people upgrading who are targeting ~1.7.0

**Comment by kalmeshnfk** [comment]
@billinghamj should we upgrade to 1.8.0? is it stable enough for adoption?

**Comment by billinghamj** [comment]
@kalmeshnfk Honestly hard for me to say. I don't really use it any more! Would just suggest being cautious and testing carefully

**Comment by kalmeshnfk** [comment]
hmmm sure. thanks :)
