### ISSUE TITLE
Value getting nil

### ISSUE THREAD

**Issue by Shiv-kiwitech** [JSONModel/JSONModel#653]
Hi, 
I have response with array of dictionary and I have key("featured" type NSNumber) in json object but after getting in model it turn nil.
({
           "exclude_from_main_feed" = 0;
            featured = 1; // Number
            "feed_image_height" = 2080;
            "feed_image_width" = 960;
            "forum_groups" =             (
            );
})

**Comment by weevilgenius** [comment]
To deserialize a collection (array or dictionary) of objects, you'll need to correctly decorate the class property so that JSONModel knows what to instantiate. In particular, you may have to add an empty protocol to your class header which you can then use for the collection property. Take a look at the [Model Collections](https://github.com/jsonmodel/jsonmodel#model-collections) section in the documentation for more details and some examples.

**Comment by Shiv-kiwitech** [comment]
Thanks
